name: Serenity BDD Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: '16.0.2'
        distribution: 'temurin'
        cache: gradle

    - uses: browser-actions/setup-chrome@latest
    - run: google-chrome --version  # Verificar la versión de Chrome

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew  # Otorga permiso de ejecución a gradlew

    - name: Build with Gradle
      run: ./gradlew clean test  # Ejecuta el build y las pruebas

    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()  # Subir el reporte sin importar el resultado del build
      with:
        name: Serenity Report
        path: target/site/serenity  # Ruta del reporte de Serenity
