name: Serenity BDD Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: '16.0.2'
        distribution: 'temurin'
        cache: gradle

    - uses: browser-actions/setup-chrome@latest
    - run: google-chrome --version  # Verificar la versión de Chrome

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew  # Otorga permiso de ejecución a gradlew

    - name: Start Server
      run: |
        cd ./recursos/login/login.html
        nohup python3 -m http.server 5500 &  # Inicia un servidor en el puerto 5500 en segundo plano
        sleep 10  # Espera 10 segundos para que el servidor esté listo

    - name: Check Server Availability
      run: |
        curl -I http://127.0.0.1:5500/login.html  # Verifica que el servidor esté disponible

    - name: Build with Gradle
      run: ./gradlew clean test  # Ejecuta el build y las pruebas

    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()  # Subir el reporte sin importar el resultado del build
      with:
        name: Serenity Report
        path: target/site/serenity  # Ruta del reporte de Serenity
