name: Serenity BDD Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Obtiene el código fuente del repositorio

    - name: Set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: '16.0.2'
        distribution: 'temurin'
        cache: gradle

    - uses: browser-actions/setup-chrome@latest
      run: google-chrome --version  # Verifica la versión de Chrome

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew  # Otorga permiso de ejecución a gradlew

    - name: Start Server
      run: |
        nohup python3 -m http.server 5500 &  # Inicia el servidor en segundo plano en el puerto 5500

    - name: Check if login.html is accessible
      run: |
        curl -I http://127.0.0.1:5500/recursos/login/login.html  # Verifica que el archivo sea accesible

    - name: Build with Gradle
      run: ./gradlew clean test  # Ejecuta el build y las pruebas

    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()  # Subir el reporte sin importar el resultado del build
      with:
        name: Serenity Report
        path: target/site/serenity 
